#!/bin/bash
PUBLIC_DNS=$(curl -s http://169.254.169.254/latest/meta-data/public-hostname)
PRIVATE_DNS=$(curl -s http://169.254.169.254/latest/meta-data/local-hostname)
echo "Public DNS: $PUBLIC_DNS"
echo "Private DNS: $PRIVATE_DNS"
